activation: torch.nn.LeakyReLU()
average: weighted
base_encoder: paraphrase-mpnet-base-v2
criterion: torch.nn.CrossEntropyLoss(reduction='none')
data_path: /content/KeyClass/scripts/data/
dataset: imdb
device: cuda
end_model_batch_size: 128
end_model_epochs: 20
end_model_lr: 1e-4
end_model_patience: 3
end_model_weight_decay: 1e-4
h_sizes:
- 768
- 256
- 64
- 2
label_model: data_programming
label_model_lr: 0.01
label_model_n_epochs: 100
max_num: 7000
min_df: 0.001
model_path: ../models/imdb/
n_bootstrap: 100
n_classes: 2
n_jobs: 10
ngram_range: !!python/tuple
- 1
- 3
normalize_embeddings: false
preds_path: ../results/imdb/
q_update_interval: 50
results_path: ../results/imdb/
self_train_batch_size: 8
self_train_lr: 1e-6
self_train_patience: 3
self_train_thresh: 1-2e-3
self_train_weight_decay: 1e-4
show_progress_bar: true
target_0: negative, hate, expensive, bad, poor, broke, waste, horrible, would not
  recommend
target_1: good, positive, excellent, amazing, love, fine, good quality, would recommend
topk: 300
use_custom_encoder: false
use_noise_aware_loss: true
